### ISSUE TITLE
Speech.py: pygame.error: mpg123_seek: Invalid RVA mode.

### ISSUE THREAD

**Issue by KazutoKashima** [KazutoKashima/Project-Red-Alice-Rising#2]
Speech.py (as stated in the title) works perfectly fine until well, you hit the Speak button, then it returns the following error:

```
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 28229.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Project-Red-Alice-Rising\src\speech.py", line 41, in buttonClick
    mixer.music.play(1)
pygame.error: mpg123_seek: Invalid RVA mode. (code 12)
```
I assumed it was due to the audio being played and ended before it was actually played, so I added a timer. Didn't work. I checked that the `chime.mp3` could be played through a media player. It did. But it still returns the `Invalid RVA`.

Maybe an issue with the file, itself? I'll try to find another audio file and test it and post the results in the issue string

**Comment by KazutoKashima** [comment]
Found issue origin, it was indeed the chime file, looking for a new one now, a quick fix is to comment out the playing of the sound

**Comment by KazutoKashima** [comment]
Changed the audio file and it worked fine on my end, will push the update when I can
